# vocab.py  ── domain vocabulary registry for Whisper initial_prompt
# Each key is a category. select_vocab() picks the right ones based on job title keywords.
# ── Coverage ──────────────────────────────────────────────────────────────────
#  common · software · ai_ml · cybersecurity · cloud · data · bi · devops
#  mobile · embedded_iot · project_management · accounting_finance · hr_talent
#  legal_compliance · marketing_growth · sales_crm · product_management
#  ux_design · qa_testing · networking · blockchain_web3 · game_dev
#  erp_sap · healthcare_it · edtech · scientific_research · robotics_automation
#  database_admin · technical_writing · support_sysadmin · supply_chain_logistics
# ──────────────────────────────────────────────────────────────────────────────

_VOCAB: dict[str, list[str]] = {

    # ── Always included ───────────────────────────────────────────────────────
    "common": [
        "VERMEG", "fintech", "banking", "insurance", "Sophis", "Colosseum",
        "IEEE", "agile", "scrum", "kanban", "sprint", "JIRA", "Confluence",
        "Git", "GitHub", "GitLab", "pull request", "merge conflict", "branching",
        "CI/CD", "DevOps", "Docker", "Kubernetes", "Linux", "REST API", "JSON", "YAML",
        "microservices", "monolith", "API gateway", "load balancer", "caching",
        "PostgreSQL", "MySQL", "MongoDB", "Redis", "SQL", "NoSQL",
        "stakeholder", "deliverable", "milestone", "SLA", "KPI", "OKR",
        "onboarding", "offboarding", "escalation", "roadmap", "backlog",
        "proof of concept", "PoC", "MVP", "minimum viable product",
        "technical debt", "refactoring", "code review", "peer review",
        "architecture", "design pattern", "best practice", "documentation",
        "regression", "deployment", "release", "hotfix", "patch",
        "performance", "scalability", "reliability", "availability",
        "SaaS", "PaaS", "IaaS", "on-premise", "hybrid", "cloud-native",
    ],

    # ── Software Engineering ──────────────────────────────────────────────────
    "software": [
        # JVM ecosystem
        "Java", "Spring Boot", "Spring Framework", "Spring Data JPA", "Hibernate",
        "Maven", "Gradle", "Spring Security", "Spring MVC", "Spring Cloud",
        "@RestController", "@ControllerAdvice", "@NotNull", "@Transactional",
        "@Entity", "@Service", "@Repository", "@Component", "@Autowired",
        "@Configuration", "@Bean", "@Qualifier", "@Value", "@Profile",
        "DTO", "CRUD", "ORM", "JPA", "JDBC", "JMS", "JMX",
        "Lombok", "MapStruct", "Flyway", "Liquibase",
        "Quarkus", "Micronaut", "Vert.x", "Dropwizard",
        "Kotlin", "Scala", "Groovy", "Clojure",
        # Python ecosystem
        "Python", "Django", "FastAPI", "Flask", "Pydantic", "SQLAlchemy",
        "Celery", "asyncio", "aiohttp", "uvicorn", "gunicorn",
        "virtual environment", "pip", "poetry", "conda",
        # JavaScript / TypeScript
        "Node.js", "Express", "NestJS", "TypeScript", "JavaScript", "ES6",
        "React", "Angular", "Vue", "Next.js", "Nuxt.js", "Svelte",
        "Redux", "Zustand", "RxJS", "Webpack", "Vite", "Rollup", "esbuild",
        "npm", "yarn", "pnpm", "Babel", "ESLint", "Prettier",
        # PHP
        "PHP", "Laravel", "Symfony", "Composer", "Eloquent", "Doctrine",
        # .NET
        "C#", ".NET", "ASP.NET Core", "Entity Framework", "LINQ",
        "Blazor", "SignalR", "NuGet", "Razor",
        # Go
        "Go", "Golang", "Gin", "Echo", "Fiber", "goroutine", "channel",
        # Rust
        "Rust", "Cargo", "Tokio", "Actix", "ownership", "borrowing", "lifetime",
        # Ruby
        "Ruby", "Rails", "Ruby on Rails", "Gem", "ActiveRecord", "Sinatra",
        # Functional & misc
        "Haskell", "Erlang", "Elixir", "Phoenix", "Elm",
        # Patterns & principles
        "design patterns", "SOLID", "DRY", "KISS", "YAGNI",
        "clean architecture", "hexagonal architecture", "domain-driven design", "DDD",
        "event-driven architecture", "CQRS", "event sourcing", "saga pattern",
        "repository pattern", "factory pattern", "singleton", "observer",
        "dependency injection", "inversion of control", "IoC",
        # Testing
        "unit testing", "integration testing", "end-to-end testing", "E2E",
        "JUnit", "Mockito", "TestNG", "AssertJ", "Hamcrest",
        "pytest", "unittest", "hypothesis",
        "Jest", "Vitest", "Mocha", "Chai", "Cypress", "Playwright", "Selenium",
        "test coverage", "code coverage", "mutation testing",
        "TDD", "test-driven development", "BDD", "behaviour-driven development",
        "Gherkin", "Cucumber", "SpecFlow",
        # APIs & protocols
        "WebSockets", "gRPC", "GraphQL", "OpenAPI", "Swagger",
        "REST", "SOAP", "WSDL", "XML", "Protobuf", "Avro", "MessagePack",
        # Build & tooling
        "Make", "CMake", "Bazel", "Ant",
        "SonarQube", "Checkstyle", "PMD", "SpotBugs",
        "IntelliJ IDEA", "VS Code", "Eclipse", "NetBeans",
    ],

    # ── AI / ML / Data Science ────────────────────────────────────────────────
    "ai_ml": [
        # Foundations
        "machine learning", "deep learning", "neural network", "artificial intelligence",
        "supervised learning", "unsupervised learning", "semi-supervised learning",
        "self-supervised learning", "reinforcement learning", "transfer learning",
        "meta-learning", "few-shot learning", "zero-shot learning",
        # Algorithms
        "linear regression", "logistic regression", "decision tree", "random forest",
        "gradient boosting", "XGBoost", "LightGBM", "CatBoost",
        "support vector machine", "SVM", "k-nearest neighbours", "KNN",
        "naive Bayes", "k-means", "DBSCAN", "hierarchical clustering",
        "principal component analysis", "PCA", "t-SNE", "UMAP",
        "classification", "regression", "clustering", "anomaly detection",
        "dimensionality reduction", "feature selection", "feature engineering",
        # Deep learning
        "transformer", "attention mechanism", "self-attention", "multi-head attention",
        "BERT", "GPT", "T5", "LLaMA", "Mistral", "Gemma",
        "convolutional neural network", "CNN", "recurrent neural network", "RNN",
        "LSTM", "GRU", "encoder-decoder", "autoencoder", "variational autoencoder",
        "generative adversarial network", "GAN", "diffusion model",
        "batch normalisation", "dropout", "residual connection", "skip connection",
        "activation function", "ReLU", "sigmoid", "softmax", "tanh",
        "backpropagation", "gradient descent", "Adam", "SGD", "learning rate",
        "weight initialisation", "Xavier", "He initialisation",
        # LLMs & GenAI
        "LLM", "large language model", "fine-tuning", "LoRA", "QLoRA",
        "RLHF", "instruction tuning", "prompt engineering", "chain of thought",
        "RAG", "retrieval-augmented generation", "embeddings", "vector database",
        "Pinecone", "Weaviate", "Chroma", "FAISS", "Milvus", "Qdrant",
        "semantic search", "dense retrieval", "hybrid search",
        "LangChain", "LlamaIndex", "Haystack", "DSPy",
        "OpenAI", "Anthropic", "Cohere", "Hugging Face",
        "tokenisation", "BPE", "SentencePiece", "tiktoken",
        "context window", "temperature", "top-p sampling", "beam search",
        # Frameworks & libraries
        "PyTorch", "TensorFlow", "Keras", "JAX", "Flax", "Paddle",
        "scikit-learn", "statsmodels", "scipy",
        "pandas", "numpy", "matplotlib", "seaborn", "plotly",
        "ONNX", "TensorRT", "OpenVINO", "GGUF", "llama.cpp",
        "vLLM", "Triton Inference Server", "BentoML", "Seldon",
        # NLP
        "natural language processing", "NLP", "text classification", "NER",
        "named entity recognition", "sentiment analysis", "relation extraction",
        "machine translation", "summarisation", "question answering",
        "word2vec", "GloVe", "fastText",
        "lemmatisation", "stemming", "tokenisation", "POS tagging",
        "spaCy", "NLTK", "Gensim", "stanza",
        # Computer vision
        "computer vision", "image classification", "object detection",
        "semantic segmentation", "instance segmentation", "panoptic segmentation",
        "YOLO", "YOLOv8", "Detectron2", "MMDetection",
        "OpenCV", "Pillow", "albumentations", "torchvision",
        "image augmentation", "data augmentation",
        "Stable Diffusion", "DALL-E", "ControlNet", "LoRA",
        "OCR", "Tesseract", "PaddleOCR",
        "pose estimation", "depth estimation", "optical flow",
        # Speech & audio
        "speech recognition", "ASR", "TTS", "text-to-speech",
        "Whisper", "wav2vec", "HiFi-GAN", "Tacotron",
        "librosa", "torchaudio", "pyaudio",
        "speaker diarisation", "speaker identification",
        "mel spectrogram", "MFCC", "feature extraction",
        # MLOps
        "MLflow", "Weights and Biases", "wandb", "Neptune", "Comet",
        "Kubeflow", "Airflow", "Prefect", "Metaflow", "ZenML",
        "model registry", "model serving", "model monitoring",
        "data pipeline", "ETL", "feature store", "Feast", "Tecton",
        "A/B testing", "shadow deployment", "canary model",
        "model drift", "data drift", "concept drift",
        "explainability", "SHAP", "LIME", "Grad-CAM",
        "fairness", "bias", "responsible AI", "AI ethics",
        "hyperparameter tuning", "cross-validation", "k-fold",
        "confusion matrix", "precision", "recall", "F1 score",
        "ROC AUC", "PR curve", "mean average precision", "mAP",
        "BLEU", "ROUGE", "perplexity",
    ],

    # ── Cybersecurity ─────────────────────────────────────────────────────────
    "cybersecurity": [
        # Offensive
        "penetration testing", "pen test", "ethical hacking", "red team",
        "vulnerability assessment", "exploit", "payload", "shellcode",
        "privilege escalation", "lateral movement", "persistence",
        "post-exploitation", "Metasploit", "Cobalt Strike", "Empire",
        "Kali Linux", "Parrot OS", "BlackArch",
        "Burp Suite", "OWASP ZAP", "sqlmap", "Hydra", "John the Ripper",
        "Hashcat", "Mimikatz", "BloodHound", "PowerView",
        "Nmap", "Masscan", "Shodan", "recon", "OSINT",
        "social engineering", "phishing", "spear phishing", "vishing",
        "watering hole", "pretexting", "baiting",
        # Vulnerabilities
        "OWASP Top 10", "SQL injection", "XSS", "cross-site scripting",
        "CSRF", "cross-site request forgery", "SSRF", "server-side request forgery",
        "XXE", "XML external entity", "IDOR", "insecure direct object reference",
        "path traversal", "directory traversal", "file inclusion",
        "command injection", "buffer overflow", "heap overflow", "stack overflow",
        "use-after-free", "format string", "integer overflow",
        "race condition", "TOCTOU", "deserialization",
        "man-in-the-middle", "MITM", "ARP poisoning", "DNS poisoning",
        "zero-day", "CVE", "CVSS", "CWE", "NVD", "Exploit DB",
        # Defensive
        "blue team", "purple team", "SOC", "CSIRT", "CERT",
        "SIEM", "Splunk", "IBM QRadar", "Microsoft Sentinel", "Elastic SIEM",
        "IDS", "IPS", "Snort", "Suricata", "Zeek",
        "EDR", "XDR", "CrowdStrike", "SentinelOne", "Carbon Black",
        "WAF", "web application firewall", "ModSecurity", "Cloudflare",
        "firewall", "iptables", "pfSense", "Palo Alto", "Fortinet", "Cisco ASA",
        "DLP", "data loss prevention", "CASB",
        "SOAR", "security orchestration", "automation", "response",
        "threat intelligence", "threat hunting", "IOC", "indicator of compromise",
        "TTPs", "MITRE ATT&CK", "kill chain", "cyber kill chain",
        "incident response", "digital forensics", "DFIR",
        "memory forensics", "disk forensics", "Volatility", "Autopsy", "FTK",
        "malware analysis", "reverse engineering", "sandboxing", "dynamic analysis",
        "IDA Pro", "Ghidra", "radare2", "x64dbg", "OllyDbg",
        # Cryptography
        "encryption", "decryption", "symmetric encryption", "asymmetric encryption",
        "AES", "RSA", "ECC", "elliptic curve", "ChaCha20",
        "SHA-256", "SHA-3", "MD5", "bcrypt", "Argon2", "PBKDF2",
        "TLS", "SSL", "mTLS", "PKI", "certificate authority", "CA",
        "X.509", "digital signature", "HMAC", "key exchange", "Diffie-Hellman",
        "end-to-end encryption", "E2EE", "HSM", "hardware security module",
        "homomorphic encryption", "zero-knowledge proof",
        # IAM & access
        "authentication", "authorisation", "OAuth 2.0", "SAML", "OIDC",
        "JWT", "MFA", "TOTP", "FIDO2", "WebAuthn", "passkey",
        "zero trust", "least privilege", "RBAC", "ABAC", "PAM",
        "Active Directory", "LDAP", "SSO", "single sign-on",
        "Okta", "Azure AD", "Entra ID", "CyberArk",
        # Compliance & frameworks
        "NIST", "ISO 27001", "SOC 2", "GDPR", "PCI DSS", "HIPAA",
        "NIS2", "DORA", "FedRAMP", "CMMC",
        "risk management", "risk assessment", "threat modeling",
        "STRIDE", "DREAD", "PASTA", "attack tree",
        "defense in depth", "security by design", "shift-left security",
        "DevSecOps", "SAST", "DAST", "IAST", "SCA",
        "Snyk", "Checkmarx", "Veracode", "SonarQube",
        "Wireshark", "tcpdump", "NetworkMiner",
    ],

    # ── Cloud & Infrastructure ────────────────────────────────────────────────
    "cloud": [
        # AWS
        "AWS", "Amazon Web Services", "EC2", "S3", "Lambda", "RDS", "DynamoDB",
        "EKS", "ECS", "Fargate", "ECR", "Elastic Beanstalk",
        "CloudFormation", "CDK", "SAM", "Amplify",
        "VPC", "subnet", "security group", "NACL", "route table",
        "IAM", "STS", "Cognito", "Secrets Manager", "Parameter Store",
        "CloudWatch", "CloudTrail", "Config", "GuardDuty", "Security Hub",
        "SQS", "SNS", "EventBridge", "Kinesis", "MSK",
        "CloudFront", "Route 53", "API Gateway", "ALB", "NLB",
        "Glacier", "EFS", "EBS", "FSx",
        "Redshift", "Aurora", "ElastiCache", "OpenSearch",
        "Step Functions", "Glue", "EMR", "Athena", "Lake Formation",
        "SageMaker", "Rekognition", "Comprehend", "Textract",
        "Savings Plans", "Reserved Instances", "Spot Instances", "FinOps",
        "AWS Organizations", "Control Tower", "Landing Zone",
        # Azure
        "Azure", "Microsoft Azure", "Azure DevOps", "Azure Pipelines",
        "Azure Functions", "Azure App Service", "Azure Kubernetes Service", "AKS",
        "Azure Blob Storage", "Azure Data Lake", "Azure SQL", "Cosmos DB",
        "Azure Event Hub", "Azure Service Bus", "Azure Logic Apps",
        "Azure Active Directory", "Entra ID", "Azure AD",
        "Azure Monitor", "Application Insights", "Log Analytics",
        "Azure Policy", "Management Groups", "Blueprints",
        "Azure Synapse", "Azure Databricks", "Azure Machine Learning",
        "Azure Container Registry", "Azure Container Apps",
        "ARM templates", "Bicep",
        # GCP
        "GCP", "Google Cloud Platform", "Google Cloud",
        "Compute Engine", "Cloud Run", "Cloud Functions", "GKE",
        "BigQuery", "Cloud Spanner", "Cloud SQL", "Firestore", "Bigtable",
        "Cloud Storage", "Persistent Disk",
        "Pub/Sub", "Dataflow", "Dataproc", "Composer",
        "Vertex AI", "AutoML", "Vision AI", "Natural Language API",
        "Cloud Armor", "Identity Platform", "Secret Manager",
        "Deployment Manager", "Config Connector",
        # Multi-cloud & shared
        "Kubernetes", "K8s", "kubectl", "kubeadm", "kops",
        "Helm", "Helmfile", "Kustomize", "ArgoCD", "Flux",
        "Istio", "Linkerd", "Consul", "service mesh", "sidecar",
        "Envoy", "Traefik", "nginx ingress",
        "Terraform", "Terragrunt", "OpenTofu",
        "Ansible", "Puppet", "Chef", "Salt",
        "Pulumi", "Crossplane",
        "Packer", "Vagrant",
        "Infrastructure as Code", "IaC", "GitOps",
        "serverless", "event-driven", "function as a service", "FaaS",
        "RabbitMQ", "Kafka", "NATS", "ActiveMQ",
        "Prometheus", "Grafana", "Thanos", "Cortex",
        "OpenTelemetry", "Jaeger", "Zipkin", "distributed tracing",
        "Datadog", "New Relic", "Dynatrace", "AppDynamics",
        "auto-scaling", "horizontal pod autoscaler", "HPA", "VPA",
        "CDN", "edge computing", "PoP", "point of presence",
        "multi-cloud", "hybrid cloud", "cloud migration", "lift and shift",
        "replatforming", "refactoring", "cloud-native",
        "FinOps", "cost optimisation", "rightsizing",
        "disaster recovery", "RTO", "RPO", "business continuity",
        "availability zones", "regions", "data residency",
    ],

    # ── Data Engineering ──────────────────────────────────────────────────────
    "data": [
        # Processing engines
        "Apache Spark", "PySpark", "Spark SQL", "Spark Streaming",
        "Apache Kafka", "Kafka Streams", "KSQL", "Confluent",
        "Apache Flink", "Apache Beam", "Apache Storm",
        "Apache Airflow", "Prefect", "Dagster", "Luigi", "Mage",
        "dbt", "dbt Core", "dbt Cloud", "Jaffle Shop",
        # Storage & warehouses
        "Snowflake", "Databricks", "Delta Lake", "Apache Iceberg", "Apache Hudi",
        "data lakehouse", "data warehouse", "data lake", "data mart",
        "BigQuery", "Redshift", "Azure Synapse", "Teradata", "Exasol",
        "Amazon S3", "Azure Data Lake Storage", "Google Cloud Storage",
        "Apache Parquet", "Apache Avro", "Apache ORC", "Delta format",
        # Databases
        "PostgreSQL", "MySQL", "MariaDB", "SQLite",
        "MongoDB", "Cassandra", "HBase", "CouchDB",
        "Redis", "Memcached", "DynamoDB", "Firestore",
        "ClickHouse", "Apache Druid", "Apache Pinot",
        "Elasticsearch", "OpenSearch", "Solr",
        "Neo4j", "TigerGraph", "Amazon Neptune",
        "TimescaleDB", "InfluxDB", "Prometheus", "VictoriaMetrics",
        # SQL skills
        "SQL", "window functions", "CTEs", "common table expressions",
        "stored procedures", "views", "materialised views", "indexes",
        "query optimisation", "explain plan", "vacuum", "ANALYZE",
        "partitioning", "sharding", "replication", "ACID",
        "transactions", "locking", "deadlock", "isolation level",
        # Modeling
        "data modeling", "star schema", "snowflake schema",
        "dimensional modeling", "Kimball", "Inmon",
        "fact table", "dimension table", "SCD", "slowly changing dimension",
        "data vault", "one big table", "OBT",
        "entity-relationship diagram", "ERD",
        # Libraries
        "pandas", "polars", "Dask", "Vaex", "cuDF",
        "numpy", "scipy", "pyarrow",
        # Quality & governance
        "data quality", "data lineage", "data catalog",
        "Apache Atlas", "OpenMetadata", "Collibra", "Alation",
        "Great Expectations", "Soda", "Monte Carlo",
        "data governance", "data mesh", "data product",
        "master data management", "MDM",
        # Patterns
        "ETL", "ELT", "streaming", "batch processing", "micro-batch",
        "CDC", "change data capture", "Debezium",
        "lambda architecture", "kappa architecture",
        "real-time analytics", "OLAP", "OLTP",
        "data contract", "schema registry",
    ],

    # ── Business Intelligence ─────────────────────────────────────────────────
    "bi": [
        "business intelligence", "BI", "analytics", "reporting",
        "Power BI", "Tableau", "Looker", "Qlik", "Qlik Sense",
        "Metabase", "Apache Superset", "Google Looker Studio", "Mode",
        "Sisense", "MicroStrategy", "SAP BusinessObjects", "Oracle OBIEE",
        "DAX", "MDX", "M language", "Power Query",
        "measures", "calculated columns", "row-level security", "RLS",
        "OLAP", "cube", "dimension", "measure", "hierarchy", "KPI",
        "drill-down", "drill-through", "drill-across", "slice and dice",
        "dashboard", "scorecard", "report", "paginated report",
        "data storytelling", "data visualisation", "executive dashboard",
        "bar chart", "line chart", "scatter plot", "heat map", "treemap",
        "waterfall chart", "funnel chart", "Gantt chart",
        "star schema", "fact table", "dimension table",
        "ETL", "data mart", "data warehouse",
        "Excel", "pivot table", "Power Pivot", "Power Query",
        "VBA", "macro",
        "Google Sheets", "Google Data Studio",
        "semantic layer", "Looker LookML", "metrics layer",
        "embedded analytics", "self-service BI",
        "data refresh", "DirectQuery", "Import mode", "composite model",
    ],

    # ── DevOps / SRE / Platform ────────────────────────────────────────────────
    "devops": [
        "DevOps", "SRE", "site reliability engineering", "platform engineering",
        # CI/CD
        "CI/CD", "continuous integration", "continuous delivery", "continuous deployment",
        "Jenkins", "Jenkins X", "GitHub Actions", "GitLab CI", "CircleCI",
        "ArgoCD", "Flux", "Spinnaker", "Tekton", "Drone",
        "Bitrise", "Fastlane", "AppCenter",
        "pipeline", "stage", "job", "runner", "agent", "artifact",
        # Containers
        "Docker", "Dockerfile", "docker-compose", "BuildKit", "Kaniko",
        "Kubernetes", "K8s", "pod", "deployment", "ReplicaSet", "StatefulSet",
        "DaemonSet", "CronJob", "Job", "namespace", "ConfigMap", "Secret",
        "PersistentVolume", "PVC", "StorageClass", "Ingress",
        "Helm", "Helmfile", "Kustomize", "RBAC", "ServiceAccount",
        "Istio", "Linkerd", "Consul Connect", "Envoy",
        "containerd", "CRI-O", "podman", "buildah",
        # IaC
        "Terraform", "Terragrunt", "OpenTofu", "HCL",
        "Ansible", "playbook", "role", "inventory", "vault",
        "Puppet", "Chef", "Salt", "Pulumi", "Crossplane",
        "GitOps", "infrastructure as code", "IaC",
        # Observability
        "observability", "monitoring", "alerting", "logging",
        "Prometheus", "Grafana", "Thanos", "Cortex", "Loki",
        "Elasticsearch", "Logstash", "Kibana", "ELK stack", "EFK stack",
        "Datadog", "New Relic", "Dynatrace", "AppDynamics",
        "OpenTelemetry", "Jaeger", "Zipkin", "tracing", "span",
        "SLO", "SLI", "SLA", "error budget", "burn rate",
        "on-call", "PagerDuty", "OpsGenie", "VictorOps",
        "runbook", "playbook", "postmortem", "blameless postmortem",
        # Reliability patterns
        "chaos engineering", "Chaos Monkey", "Gremlin",
        "blue-green deployment", "canary deployment", "feature flag",
        "rollback", "rollout", "progressive delivery",
        "circuit breaker", "bulkhead", "retry", "backoff", "rate limiting",
        "health check", "liveness probe", "readiness probe", "startup probe",
        # Networking & Linux
        "Linux", "bash", "shell scripting", "cron", "systemd", "journald",
        "iptables", "nftables", "netfilter", "tc", "ip route",
        "DNS", "TCP/IP", "UDP", "HTTP", "HTTP/2", "HTTP/3", "QUIC",
        "TLS", "mTLS", "certificate", "nginx", "HAProxy", "Traefik",
        "VPN", "WireGuard", "OpenVPN", "BGP", "OSPF",
    ],

    # ── Mobile Development ─────────────────────────────────────────────────────
    "mobile": [
        "iOS", "Android", "Swift", "Objective-C", "Kotlin", "Java",
        "SwiftUI", "UIKit", "Combine", "async/await", "Swift Package Manager",
        "Jetpack Compose", "Android Jetpack", "Coroutines", "Flow", "LiveData",
        "ViewModel", "Navigation Component", "WorkManager", "Room",
        "Flutter", "Dart", "Widgets", "State management",
        "BLoC", "Provider", "Riverpod", "GetX", "MobX",
        "React Native", "Expo", "Metro bundler",
        "Xamarin", "MAUI", ".NET MAUI", "Ionic", "Capacitor",
        "Xcode", "Android Studio", "Instruments", "Android Profiler",
        "CocoaPods", "Carthage", "Gradle", "ProGuard", "R8",
        "App Store", "Google Play", "TestFlight", "Firebase App Distribution",
        "push notifications", "APNs", "FCM", "Firebase Cloud Messaging",
        "deep linking", "universal links", "app links",
        "SQLite", "Realm", "Core Data", "Room database",
        "Keychain", "EncryptedSharedPreferences", "biometrics", "Face ID",
        "ARKit", "ARCore", "SceneKit", "Metal", "Vulkan",
        "in-app purchase", "StoreKit", "Google Play Billing",
        "analytics", "Firebase Analytics", "Mixpanel", "Amplitude",
        "crash reporting", "Firebase Crashlytics", "Sentry",
        "A/B testing", "feature flags", "Firebase Remote Config",
        "MVVM", "MVC", "MVP", "VIPER", "Clean Architecture",
        "unit testing", "UI testing", "XCTest", "Espresso", "Detox",
        "CI/CD", "Fastlane", "Bitrise", "GitHub Actions",
        "accessibility", "VoiceOver", "TalkBack", "a11y",
        "localisation", "l10n", "internationalisation", "i18n",
        "dark mode", "adaptive layouts", "responsive design",
        "performance profiling", "memory leaks", "battery optimisation",
        "offline first", "sync", "conflict resolution",
    ],

    # ── Embedded Systems & IoT ────────────────────────────────────────────────
    "embedded_iot": [
        "embedded systems", "firmware", "bare metal", "low-level programming",
        "C", "C++", "assembly", "MISRA C", "AUTOSAR",
        "RTOS", "real-time operating system", "FreeRTOS", "Zephyr", "VxWorks",
        "ThreadX", "RTEMS", "mbed OS", "ChibiOS",
        "microcontroller", "MCU", "STM32", "ESP32", "ESP8266",
        "Arduino", "Raspberry Pi", "BeagleBone", "NXP", "Nordic nRF",
        "PIC", "AVR", "MSP430",
        "FPGA", "CPLD", "VHDL", "Verilog", "SystemVerilog",
        "Xilinx", "Altera", "Intel FPGA", "Lattice",
        "Vivado", "Quartus", "ModelSim",
        "UART", "SPI", "I2C", "I2S", "CAN bus", "LIN bus",
        "Modbus", "Profibus", "EtherCAT", "PROFINET",
        "MQTT", "CoAP", "AMQP", "Zigbee", "Z-Wave", "LoRaWAN", "BLE",
        "IoT", "edge computing", "fog computing",
        "sensor", "actuator", "transducer", "ADC", "DAC",
        "PWM", "timer", "interrupt", "DMA", "direct memory access",
        "bootloader", "OTA update", "secure boot", "code signing",
        "power consumption", "low power design", "sleep mode", "deep sleep",
        "watchdog timer", "WDT", "reset", "brownout",
        "PCB", "PCB design", "schematic", "KiCad", "Altium",
        "oscilloscope", "logic analyzer", "JTAG", "SWD", "OpenOCD",
        "memory map", "flash", "EEPROM", "RAM", "ROM",
        "HAL", "hardware abstraction layer", "BSP", "board support package",
        "device driver", "kernel module", "Linux kernel",
        "Yocto", "Buildroot", "OpenWRT",
        "automotive", "functional safety", "ISO 26262", "IEC 61508",
        "DO-178C", "ARINC", "RTCA",
    ],

    # ── Project Management ────────────────────────────────────────────────────
    "project_management": [
        "project management", "programme management", "portfolio management",
        "PMP", "PRINCE2", "PRINCE2 Agile", "PMI", "PMBOK",
        "agile", "scrum", "kanban", "lean", "SAFe", "Scaled Agile Framework",
        "LeSS", "Large-Scale Scrum", "Nexus", "Disciplined Agile",
        "waterfall", "hybrid methodology", "iterative", "incremental",
        "sprint", "iteration", "timebox", "velocity", "capacity",
        "sprint planning", "sprint review", "sprint retrospective",
        "daily scrum", "daily standup", "three questions",
        "backlog refinement", "grooming", "estimation", "story points",
        "planning poker", "T-shirt sizing",
        "product owner", "scrum master", "agile coach", "delivery manager",
        "project manager", "programme manager", "PMO",
        "project charter", "project brief", "initiation document",
        "scope", "scope creep", "change request", "change control",
        "stakeholder management", "stakeholder register", "RACI",
        "risk register", "issue log", "RAID log", "assumptions log",
        "work breakdown structure", "WBS", "Gantt chart", "critical path",
        "critical path method", "CPM", "network diagram", "PERT",
        "earned value management", "EVM", "EV", "PV", "AC",
        "CPI", "SPI", "cost variance", "schedule variance",
        "burn-down chart", "burn-up chart", "cumulative flow diagram",
        "dependency", "blocker", "impediment", "escalation",
        "milestone", "deliverable", "acceptance criteria", "definition of done",
        "definition of ready", "user story", "epic", "feature", "task",
        "INVEST", "SMART goals", "OKR", "KPI",
        "JIRA", "Confluence", "Trello", "Asana", "Monday.com",
        "MS Project", "Smartsheet", "Notion", "Linear",
        "budget management", "cost estimation", "resource allocation",
        "resource levelling", "critical resource", "bottleneck",
        "communication plan", "status report", "steering committee",
        "lessons learned", "retrospective", "continuous improvement",
        "change management", "ADKAR", "Kotter", "Lewin",
    ],

    # ── Accounting & Finance ──────────────────────────────────────────────────
    "accounting_finance": [
        "accounting", "finance", "financial reporting",
        "IFRS", "GAAP", "US GAAP", "UK GAAP",
        "balance sheet", "income statement", "profit and loss", "P&L",
        "cash flow statement", "statement of changes in equity",
        "accounts payable", "AP", "accounts receivable", "AR",
        "general ledger", "GL", "sub-ledger", "chart of accounts",
        "trial balance", "reconciliation", "bank reconciliation",
        "journal entry", "double-entry bookkeeping", "debit", "credit",
        "accruals", "deferrals", "prepayments", "provisions",
        "depreciation", "amortisation", "impairment",
        "audit", "internal audit", "external audit", "statutory audit",
        "audit trail", "audit opinion", "management letter",
        "SOX", "Sarbanes-Oxley", "Section 404", "ICFR",
        "tax", "VAT", "GST", "corporate tax", "deferred tax",
        "transfer pricing", "tax compliance", "tax planning",
        "EBITDA", "EBIT", "gross margin", "net margin", "operating profit",
        "budgeting", "forecasting", "variance analysis", "FP&A",
        "financial planning and analysis", "rolling forecast",
        "scenario planning", "sensitivity analysis",
        "cost accounting", "standard costing", "activity-based costing", "ABC",
        "management accounting", "contribution margin", "break-even",
        "fixed costs", "variable costs", "overhead allocation",
        "working capital", "cash conversion cycle", "days sales outstanding",
        "days payable outstanding", "inventory days",
        "treasury", "liquidity management", "cash pooling", "hedging",
        "FX risk", "interest rate risk", "commodity risk",
        "investment banking", "M&A", "mergers and acquisitions",
        "due diligence", "valuation", "DCF", "discounted cash flow",
        "comparable company analysis", "precedent transactions",
        "LBO", "leveraged buyout", "PE", "private equity",
        "asset management", "portfolio management", "fund administration",
        "NAV", "net asset value", "AUM", "assets under management",
        "Basel III", "Basel IV", "Solvency II", "IFRS 9", "IFRS 17",
        "credit risk", "market risk", "operational risk", "liquidity risk",
        "VaR", "value at risk", "stress testing", "scenario analysis",
        "SAP FI", "SAP CO", "SAP S/4HANA", "Oracle Financials", "Oracle ERP",
        "QuickBooks", "Sage", "Xero", "Netsuite",
        "ERP", "enterprise resource planning",
        "procure-to-pay", "order-to-cash", "record-to-report",
        "consolidation", "intercompany", "elimination",
        "XBRL", "iXBRL", "financial data standards",
        "ESG reporting", "sustainability accounting", "CSRD", "TCFD",
    ],

    # ── HR & Talent ───────────────────────────────────────────────────────────
    "hr_talent": [
        "human resources", "HR", "talent acquisition", "talent management",
        "recruitment", "sourcing", "headhunting", "executive search",
        "job description", "job requisition", "headcount", "workforce planning",
        "applicant tracking system", "ATS", "Workday", "Greenhouse", "Lever",
        "SmartRecruiters", "BambooHR", "SAP SuccessFactors", "Oracle HCM",
        "LinkedIn Recruiter", "Indeed", "Glassdoor", "job board",
        "Boolean search", "X-ray search", "sourcing strategy",
        "interview", "structured interview", "competency-based interview",
        "behavioural interview", "STAR method", "situational interview",
        "technical interview", "case interview", "assessment centre",
        "psychometric testing", "cognitive ability test", "personality assessment",
        "pre-employment screening", "background check", "reference check",
        "offer management", "offer letter", "negotiation", "counter-offer",
        "onboarding", "induction", "orientation", "buddy system",
        "employee lifecycle", "retention", "attrition", "turnover",
        "performance management", "appraisal", "360 feedback",
        "performance improvement plan", "PIP",
        "learning and development", "L&D", "training", "upskilling", "reskilling",
        "LMS", "learning management system", "e-learning", "microlearning",
        "succession planning", "career development", "career path",
        "compensation", "benefits", "total rewards", "pay equity",
        "salary benchmarking", "job grading", "Hay grading", "Mercer",
        "employee engagement", "employee experience", "EVP",
        "employer brand", "culture", "values", "DE&I",
        "diversity equity inclusion", "belonging", "unconscious bias",
        "HRIS", "HR information system", "people analytics",
        "labour law", "employment law", "GDPR", "data protection",
        "grievance", "disciplinary", "redundancy", "TUPE",
        "collective bargaining", "works council", "union",
        "remote work", "hybrid work", "flexible working",
    ],

    # ── Legal & Compliance ────────────────────────────────────────────────────
    "legal_compliance": [
        "legal", "compliance", "regulatory affairs", "in-house counsel",
        "contract law", "contract drafting", "contract negotiation",
        "NDA", "non-disclosure agreement", "SLA", "MSA", "SOW",
        "intellectual property", "IP", "patent", "trademark", "copyright",
        "GDPR", "data protection", "data privacy", "CCPA", "LGPD",
        "privacy by design", "data subject rights", "DPO", "data protection officer",
        "DPIA", "data protection impact assessment",
        "AML", "anti-money laundering", "KYC", "know your customer",
        "KYB", "know your business", "CDD", "customer due diligence",
        "EDD", "enhanced due diligence", "PEP", "sanctions screening",
        "FATF", "FinCEN", "FCA", "ESMA", "MiFID II", "EMIR",
        "PSD2", "open banking", "strong customer authentication", "SCA",
        "Basel", "Solvency II", "DORA", "NIS2", "GDPR",
        "regulatory capital", "capital adequacy", "Pillar 1", "Pillar 2",
        "corporate governance", "board", "audit committee",
        "whistleblowing", "speak-up culture", "ethics hotline",
        "litigation", "arbitration", "mediation", "dispute resolution",
        "due diligence", "M&A legal", "deal structuring",
        "employment law", "TUPE", "redundancy", "discrimination",
        "competition law", "antitrust", "merger control",
        "FCPA", "Bribery Act", "anti-corruption",
        "legal tech", "LegalZoom", "DocuSign", "CLM",
        "contract lifecycle management", "matter management",
        "e-discovery", "litigation hold", "legal hold",
    ],

    # ── Marketing & Growth ────────────────────────────────────────────────────
    "marketing_growth": [
        "marketing", "digital marketing", "growth marketing", "performance marketing",
        "brand marketing", "content marketing", "inbound marketing",
        "SEO", "search engine optimisation", "on-page SEO", "off-page SEO",
        "technical SEO", "Core Web Vitals", "PageSpeed", "schema markup",
        "SEM", "PPC", "paid search", "Google Ads", "Microsoft Ads",
        "paid social", "Facebook Ads", "Meta Ads", "Instagram Ads",
        "LinkedIn Ads", "TikTok Ads", "Twitter Ads", "X Ads",
        "programmatic advertising", "DSP", "SSP", "DMP", "RTB",
        "social media marketing", "community management", "influencer marketing",
        "email marketing", "newsletter", "drip campaign", "lifecycle marketing",
        "Mailchimp", "HubSpot", "Klaviyo", "Braze", "Iterable", "Marketo",
        "CRM", "Salesforce", "HubSpot CRM", "Pipedrive",
        "marketing automation", "lead nurturing", "lead scoring",
        "landing page", "CRO", "conversion rate optimisation",
        "A/B testing", "multivariate testing", "split testing",
        "funnel", "TOFU", "MOFU", "BOFU", "customer journey",
        "attribution", "multi-touch attribution", "last-click", "first-click",
        "UTM parameters", "tracking pixel", "cookie", "cookieless",
        "CAC", "customer acquisition cost", "LTV", "lifetime value",
        "ROAS", "return on ad spend", "ROI", "CPM", "CPC", "CPA", "CTR",
        "growth hacking", "product-led growth", "PLG", "viral coefficient",
        "referral programme", "affiliate marketing",
        "content strategy", "editorial calendar", "copywriting",
        "SEO writing", "blog", "whitepaper", "case study", "webinar",
        "podcast", "video marketing", "YouTube", "Vimeo",
        "Google Analytics 4", "GA4", "Adobe Analytics",
        "Mixpanel", "Amplitude", "Heap", "Hotjar", "Fullstory",
        "GTM", "Google Tag Manager", "tag management",
        "first-party data", "third-party data", "data clean room",
        "CDP", "customer data platform", "Segment", "mParticle",
        "market research", "persona", "ICP", "ideal customer profile",
        "voice of customer", "NPS", "CSAT", "CES",
        "PR", "public relations", "media relations", "press release",
        "events", "trade shows", "webinars", "field marketing",
        "ABM", "account-based marketing",
    ],

    # ── Sales & CRM ───────────────────────────────────────────────────────────
    "sales_crm": [
        "sales", "enterprise sales", "B2B sales", "SaaS sales", "solution selling",
        "consultative selling", "value-based selling", "SPIN selling",
        "Challenger Sale", "MEDDIC", "MEDPIC", "BANT",
        "sales development", "SDR", "BDR", "AE", "account executive",
        "inside sales", "field sales", "channel sales", "partner sales",
        "prospecting", "cold calling", "cold email", "outbound",
        "inbound leads", "MQL", "marketing qualified lead",
        "SQL", "sales qualified lead", "SAL", "pipeline",
        "opportunity", "deal", "deal stage", "CRM",
        "Salesforce", "HubSpot", "Pipedrive", "Zoho CRM",
        "Microsoft Dynamics", "Oracle CX", "SAP CRM",
        "outreach", "Outreach.io", "SalesLoft", "Gong", "Chorus",
        "sales enablement", "content", "playbook", "battle card",
        "demo", "proof of concept", "PoC", "pilot", "trial",
        "proposal", "RFP", "RFI", "tender", "pricing",
        "negotiation", "discount", "approval workflow",
        "closing", "contract", "legal review", "procurement",
        "quota", "OTE", "on-target earnings", "commission",
        "forecast", "commit", "pipeline coverage", "win rate",
        "churn", "expansion", "upsell", "cross-sell", "renewal",
        "customer success", "CSM", "customer success manager",
        "onboarding", "health score", "QBR", "quarterly business review",
        "NRR", "net revenue retention", "ARR", "MRR", "ACV", "TCV",
        "territory planning", "account mapping", "whitespace analysis",
        "sales analytics", "revenue operations", "RevOps",
    ],

    # ── Product Management ────────────────────────────────────────────────────
    "product_management": [
        "product management", "product manager", "PM", "CPO",
        "product strategy", "product vision", "product roadmap",
        "product discovery", "user research", "market research",
        "customer interview", "jobs to be done", "JTBD",
        "persona", "user journey", "customer journey map",
        "problem statement", "opportunity statement", "hypothesis",
        "MVP", "minimum viable product", "prototype", "wireframe", "mockup",
        "user story", "epic", "feature", "initiative", "theme",
        "acceptance criteria", "definition of done", "definition of ready",
        "product backlog", "prioritisation", "RICE", "MoSCoW",
        "Kano model", "impact vs effort", "opportunity scoring",
        "OKR", "north star metric", "KPI", "AARRR", "pirate metrics",
        "acquisition", "activation", "retention", "referral", "revenue",
        "DAU", "MAU", "WAU", "stickiness", "engagement",
        "churn", "retention rate", "NPS", "CSAT", "feature adoption",
        "A/B testing", "feature flags", "LaunchDarkly", "Optimizely",
        "go-to-market", "GTM", "launch plan", "pricing strategy",
        "competitive analysis", "positioning", "differentiation",
        "product-market fit", "PMF", "growth lever",
        "agile", "scrum", "kanban", "SAFe", "sprint",
        "product owner", "stakeholder management", "cross-functional",
        "engineering", "design", "data", "marketing alignment",
        "JIRA", "Confluence", "Productboard", "Aha!", "Notion",
        "Miro", "Figma", "UserTesting", "Dovetail",
        "data-driven", "analytics", "Mixpanel", "Amplitude",
        "product analytics", "funnel analysis", "cohort analysis",
        "B2B product", "B2C product", "platform", "marketplace",
        "API product", "developer experience", "DX", "developer platform",
    ],

    # ── UX / Design ───────────────────────────────────────────────────────────
    "ux_design": [
        "UX", "user experience", "UI", "user interface", "product design",
        "interaction design", "IxD", "visual design", "graphic design",
        "motion design", "brand design", "illustration",
        "Figma", "Sketch", "Adobe XD", "InVision", "Zeplin",
        "Framer", "ProtoPie", "Principle", "Origami",
        "Adobe Creative Suite", "Photoshop", "Illustrator", "After Effects",
        "Premiere Pro", "InDesign",
        "user research", "usability testing", "contextual inquiry",
        "card sorting", "tree testing", "heuristic evaluation",
        "A/B testing", "eye tracking", "guerrilla testing",
        "persona", "empathy map", "user journey", "service blueprint",
        "wireframe", "low-fidelity", "high-fidelity", "prototype", "mockup",
        "design system", "component library", "pattern library",
        "Storybook", "Zeroheight", "Supernova",
        "atomic design", "design tokens", "spacing system", "typography",
        "colour theory", "contrast ratio", "WCAG", "accessibility",
        "colour palette", "grid system", "layout", "hierarchy",
        "Gestalt principles", "affordance", "mental model",
        "information architecture", "IA", "navigation", "sitemap",
        "user flow", "task flow", "happy path", "edge case",
        "Jobs to be Done", "JTBD", "lean UX", "double diamond",
        "design sprint", "design thinking", "human-centred design",
        "responsive design", "adaptive design", "mobile-first",
        "dark mode", "theming", "localisation",
        "CSS", "HTML", "Tailwind", "handoff", "developer collaboration",
        "design critique", "design review", "red-lining",
        "NPS", "CSAT", "usability score", "SUS", "task completion rate",
    ],

    # ── QA & Testing ──────────────────────────────────────────────────────────
    "qa_testing": [
        "quality assurance", "QA", "quality engineering", "QE",
        "software testing", "test strategy", "test plan", "test case",
        "test scenario", "test data", "test environment",
        "manual testing", "exploratory testing", "ad-hoc testing",
        "automated testing", "test automation",
        "unit testing", "integration testing", "system testing",
        "end-to-end testing", "E2E testing", "acceptance testing", "UAT",
        "regression testing", "smoke testing", "sanity testing",
        "performance testing", "load testing", "stress testing",
        "volume testing", "soak testing", "spike testing",
        "JMeter", "Gatling", "k6", "Locust",
        "security testing", "penetration testing", "DAST", "SAST",
        "accessibility testing", "compatibility testing", "cross-browser",
        "API testing", "Postman", "RestAssured", "Karate",
        "contract testing", "Pact",
        "Selenium", "WebDriver", "Playwright", "Cypress", "Puppeteer",
        "Appium", "Espresso", "XCTest", "Detox",
        "JUnit", "TestNG", "pytest", "NUnit", "xUnit",
        "Mockito", "WireMock", "Hoverfly",
        "test coverage", "branch coverage", "statement coverage",
        "mutation testing", "PIT", "Stryker",
        "BDD", "Gherkin", "Cucumber", "SpecFlow", "JBehave",
        "TDD", "test-first", "red-green-refactor",
        "shift-left testing", "DevTestOps", "continuous testing",
        "CI/CD integration", "test reporting", "Allure", "ExtentReports",
        "defect management", "bug report", "severity", "priority",
        "test management", "Zephyr", "TestRail", "Xray",
        "risk-based testing", "equivalence partitioning",
        "boundary value analysis", "decision table", "state transition",
        "pair testing", "mob testing",
        "synthetic monitoring", "real user monitoring", "RUM",
        "observability", "logging", "tracing for QA",
    ],

    # ── Networking ────────────────────────────────────────────────────────────
    "networking": [
        "networking", "network engineering", "network architecture",
        "TCP/IP", "OSI model", "Ethernet", "IEEE 802.11", "Wi-Fi 6", "Wi-Fi 6E",
        "IPv4", "IPv6", "subnetting", "CIDR", "NAT", "PAT",
        "routing", "switching", "VLAN", "trunking", "802.1Q",
        "BGP", "OSPF", "EIGRP", "RIP", "ISIS",
        "static routing", "dynamic routing", "route redistribution",
        "MPLS", "SD-WAN", "DMVPN", "GRE tunnel",
        "firewall", "stateful inspection", "packet filter", "UTM",
        "Palo Alto Networks", "Fortinet", "Cisco ASA", "Check Point",
        "IDS", "IPS", "honeypot", "DMZ",
        "VPN", "IPsec", "SSL VPN", "WireGuard", "OpenVPN", "L2TP",
        "DNS", "DHCP", "NTP", "SNMP", "NetFlow", "sFlow",
        "HTTP", "HTTPS", "FTP", "SFTP", "SSH", "Telnet",
        "TLS", "SSL", "PKI", "certificate",
        "load balancing", "F5", "Citrix ADC", "nginx", "HAProxy",
        "CDN", "Cloudflare", "Akamai", "AWS CloudFront",
        "SDN", "software-defined networking", "OpenFlow", "ONOS",
        "NFV", "network functions virtualisation",
        "Cisco", "Juniper", "Arista", "Huawei", "MikroTik",
        "IOS", "IOS-XE", "NX-OS", "JunOS", "EOS",
        "Wireshark", "tcpdump", "Nmap", "ping", "traceroute",
        "network monitoring", "PRTG", "Zabbix", "Nagios", "SolarWinds",
        "QoS", "traffic shaping", "bandwidth", "latency", "jitter",
        "5G", "LTE", "NR", "RAN", "core network",
        "datacenter networking", "spine-leaf", "CLOS topology",
        "VXLAN", "EVPN", "overlay", "underlay",
        "network automation", "Ansible", "Netmiko", "NAPALM", "pyATS",
        "RESTCONF", "NETCONF", "YANG",
        "CCNA", "CCNP", "CCIE", "JNCIA", "JNCIP",
    ],

    # ── Blockchain & Web3 ─────────────────────────────────────────────────────
    "blockchain_web3": [
        "blockchain", "distributed ledger", "DLT",
        "Bitcoin", "BTC", "Ethereum", "ETH", "Solana", "SOL",
        "Polygon", "Avalanche", "BNB Chain", "Cardano", "Polkadot",
        "Layer 1", "Layer 2", "rollup", "Optimism", "Arbitrum", "zkSync",
        "zero-knowledge proof", "ZK rollup", "optimistic rollup",
        "consensus mechanism", "proof of work", "PoW", "proof of stake", "PoS",
        "delegated proof of stake", "DPoS", "proof of authority", "PoA",
        "validator", "staking", "slashing", "epoch",
        "smart contract", "Solidity", "Vyper", "Rust on Solana",
        "EVM", "Ethereum Virtual Machine", "ABI", "bytecode",
        "Hardhat", "Foundry", "Truffle", "Remix IDE",
        "OpenZeppelin", "ERC-20", "ERC-721", "ERC-1155",
        "NFT", "non-fungible token", "fungible token", "tokenomics",
        "DeFi", "decentralised finance", "DEX", "AMM", "liquidity pool",
        "Uniswap", "Aave", "Compound", "MakerDAO", "Curve",
        "yield farming", "liquidity mining", "impermanent loss",
        "DAO", "decentralised autonomous organisation", "governance token",
        "snapshot voting", "multisig", "Gnosis Safe",
        "Web3.js", "ethers.js", "wagmi", "viem",
        "MetaMask", "WalletConnect", "Rainbow Wallet",
        "IPFS", "Filecoin", "Arweave", "decentralised storage",
        "The Graph", "Chainlink", "oracle", "price feed",
        "Infura", "Alchemy", "QuickNode", "node provider",
        "gas", "gas limit", "gas price", "EIP-1559", "base fee",
        "mempool", "transaction", "block", "hash", "nonce",
        "private key", "public key", "wallet", "seed phrase", "BIP-39",
        "audit", "smart contract audit", "formal verification",
        "reentrancy", "flash loan", "MEV", "maximal extractable value",
        "cross-chain", "bridge", "interoperability", "IBC",
        "CBDC", "central bank digital currency", "stablecoin", "USDC", "USDT",
        "KYC", "AML", "travel rule", "crypto compliance",
    ],

    # ── Game Development ──────────────────────────────────────────────────────
    "game_dev": [
        "game development", "game design", "game programming",
        "Unity", "Unreal Engine", "UE5", "Godot", "CryEngine", "Lumberyard",
        "C#", "C++", "GDScript", "Lua", "blueprint scripting",
        "rendering", "rasterisation", "ray tracing", "path tracing",
        "shader", "GLSL", "HLSL", "vertex shader", "fragment shader",
        "GPU", "draw call", "batching", "instancing", "LOD",
        "level of detail", "occlusion culling", "frustum culling",
        "lighting", "global illumination", "PBR", "physically-based rendering",
        "HDR", "tone mapping", "post-processing", "anti-aliasing",
        "physics engine", "rigid body", "collision detection",
        "Box2D", "Bullet Physics", "PhysX", "Havok",
        "animation", "skeletal animation", "blend tree", "inverse kinematics",
        "Mecanim", "Animator Controller", "motion capture", "mocap",
        "AI", "pathfinding", "A*", "NavMesh", "behaviour tree", "state machine",
        "multiplayer", "networking", "Photon", "Mirror", "Netcode", "rollback",
        "server authoritative", "client prediction", "lag compensation",
        "ECS", "entity component system", "DOTS", "Data-Oriented Design",
        "game loop", "fixed update", "frame rate", "delta time",
        "audio", "FMOD", "Wwise", "spatial audio",
        "UI", "Canvas", "immediate mode GUI", "IMGUI",
        "VR", "virtual reality", "AR", "augmented reality", "XR", "OpenXR",
        "Meta Quest", "PlayStation VR", "SteamVR",
        "Steam", "Epic Games Store", "Xbox", "PlayStation", "Nintendo Switch",
        "in-app purchase", "live ops", "monetisation", "battle pass",
        "profiling", "frame debugger", "memory profiler",
        "Git LFS", "Perforce", "version control for games",
        "Blender", "Maya", "3ds Max", "ZBrush", "Substance Painter",
        "level design", "world building", "procedural generation",
        "narrative design", "dialogue system", "quest system",
        "game balancing", "playtesting", "QA for games",
    ],

    # ── ERP / SAP / Enterprise Systems ────────────────────────────────────────
    "erp_sap": [
        "ERP", "enterprise resource planning",
        "SAP", "SAP S/4HANA", "SAP ECC", "SAP R/3",
        "SAP BTP", "SAP Business Technology Platform",
        "ABAP", "SAP Fiori", "SAP UI5", "SAP BW", "SAP HANA",
        "SAP FI", "SAP CO", "SAP MM", "SAP SD", "SAP PP", "SAP WM",
        "SAP HR", "SAP HCM", "SAP SuccessFactors",
        "SAP Ariba", "SAP Concur", "SAP IBP",
        "SAP CRM", "SAP S/4HANA Cloud", "SAP Rise",
        "Oracle ERP", "Oracle Fusion", "Oracle Cloud",
        "Oracle Financials", "Oracle HCM", "Oracle SCM",
        "Microsoft Dynamics 365", "Dynamics F&O", "Dynamics BC",
        "Power Apps", "Power Automate", "Power Platform",
        "Infor", "Epicor", "IFS", "NetSuite", "Sage",
        "business process", "business process reengineering", "BPR",
        "process mapping", "AS-IS", "TO-BE", "gap analysis",
        "functional specification", "technical specification",
        "configuration", "customisation", "enhancement", "RICEFW",
        "data migration", "go-live", "cutover", "cutover plan",
        "master data", "transactional data", "data cleansing",
        "integration", "middleware", "SAP PI", "SAP PO", "SAP CPI",
        "API", "IDoc", "BAPI", "RFC", "EDI",
        "change management", "user training", "super user",
        "testing", "SIT", "system integration testing", "UAT",
        "business analyst", "solution architect", "implementation partner",
    ],

    # ── Healthcare IT ─────────────────────────────────────────────────────────
    "healthcare_it": [
        "healthcare IT", "health informatics", "clinical informatics",
        "EHR", "electronic health record", "EMR", "electronic medical record",
        "Epic", "Cerner", "Meditech", "Allscripts", "athenahealth",
        "HL7", "HL7 FHIR", "FHIR", "HL7 v2", "CDA", "C-CDA",
        "ICD-10", "ICD-11", "SNOMED CT", "LOINC", "CPT codes",
        "DICOM", "radiology", "PACS", "RIS", "imaging informatics",
        "telehealth", "telemedicine", "remote patient monitoring",
        "clinical decision support", "CDS", "CDSS",
        "pharmacy information system", "PIS", "medication management",
        "laboratory information system", "LIS",
        "patient portal", "patient engagement", "PHR",
        "revenue cycle management", "RCM", "medical billing", "coding",
        "claims processing", "prior authorisation",
        "HIPAA", "PHI", "protected health information", "de-identification",
        "HITECH", "meaningful use", "ONC", "TEFCA", "CommonWell",
        "data exchange", "interoperability", "information blocking",
        "population health", "care management", "care coordination",
        "clinical trial", "research informatics", "REDCap",
        "NLP for clinical text", "clinical NLP", "concept extraction",
        "FDA", "CE marking", "medical device software", "SaMD",
        "IEC 62304", "ISO 14971", "risk management",
        "cybersecurity for healthcare", "HIPAA Security Rule",
        "cloud for healthcare", "HITRUST", "FedRAMP",
    ],

    # ── EdTech ────────────────────────────────────────────────────────────────
    "edtech": [
        "educational technology", "EdTech", "e-learning", "online learning",
        "LMS", "learning management system", "Moodle", "Canvas", "Blackboard",
        "Brightspace", "Schoology", "Google Classroom",
        "MOOC", "massive open online course", "Coursera", "edX", "Udemy",
        "xAPI", "TinCan API", "SCORM", "LTI", "IMS Global",
        "adaptive learning", "personalised learning", "learning path",
        "competency-based education", "CBE", "mastery learning",
        "assessment", "formative assessment", "summative assessment",
        "gamification", "badges", "leaderboard", "points",
        "virtual classroom", "Zoom for Education", "Microsoft Teams",
        "synchronous", "asynchronous", "blended learning",
        "instructional design", "ADDIE", "SAM model", "Bloom's taxonomy",
        "learning objectives", "storyboard", "course authoring",
        "Articulate Storyline", "Adobe Captivate", "Rise 360",
        "video learning", "micro-learning", "spaced repetition",
        "accessibility", "WCAG", "508 compliance",
        "student information system", "SIS", "Powerschool",
        "parent engagement", "teacher tools", "classroom management",
        "learning analytics", "xAPI", "Caliper", "predictive analytics",
    ],

    # ── Scientific Computing & Research ───────────────────────────────────────
    "scientific_research": [
        "scientific computing", "computational science", "HPC",
        "high-performance computing", "supercomputing",
        "MPI", "OpenMP", "CUDA", "OpenCL", "GPU computing",
        "parallel computing", "distributed computing",
        "MATLAB", "Octave", "Mathematica", "Maple", "Wolfram",
        "R", "Python", "Julia", "Fortran", "C++",
        "NumPy", "SciPy", "pandas", "matplotlib", "seaborn", "plotly",
        "Jupyter", "JupyterLab", "Google Colab", "Binder",
        "bioinformatics", "genomics", "proteomics", "transcriptomics",
        "BLAST", "Bowtie", "BWA", "SAMtools", "GATK",
        "Biopython", "BioConductor", "Bioconductor",
        "computational chemistry", "molecular dynamics",
        "GROMACS", "AMBER", "NAMD", "LAMMPS",
        "finite element method", "FEM", "FEA", "ANSYS", "COMSOL",
        "computational fluid dynamics", "CFD", "OpenFOAM", "Fluent",
        "Monte Carlo simulation", "Markov chain Monte Carlo", "MCMC",
        "Bayesian inference", "Stan", "PyMC3", "PyMC",
        "statistics", "hypothesis testing", "p-value", "confidence interval",
        "regression", "ANOVA", "mixed models", "multilevel models",
        "reproducible research", "version control", "Git", "DVC",
        "workflow management", "Snakemake", "Nextflow", "CWL",
        "data management", "FAIR data", "data repository", "Zenodo",
        "open science", "preprint", "arXiv", "bioRxiv",
        "LaTeX", "BibTeX", "Overleaf",
        "laboratory information system", "ELN", "electronic lab notebook",
    ],

    # ── Robotics & Automation ─────────────────────────────────────────────────
    "robotics_automation": [
        "robotics", "ROS", "ROS2", "Robot Operating System",
        "Gazebo", "RViz", "MoveIt", "Nav2",
        "SLAM", "simultaneous localisation and mapping",
        "path planning", "motion planning", "trajectory",
        "kinematics", "forward kinematics", "inverse kinematics",
        "dynamics", "torque", "Jacobian",
        "computer vision for robotics", "depth camera", "LiDAR",
        "point cloud", "PCL", "Open3D",
        "manipulation", "gripper", "end effector", "pick and place",
        "collaborative robot", "cobot", "industrial robot",
        "KUKA", "ABB", "Fanuc", "Universal Robots", "UR5", "UR10",
        "Doosan", "Boston Dynamics", "Spot", "Atlas",
        "autonomous vehicles", "AV", "ADAS", "sensor fusion",
        "radar", "LiDAR", "camera", "GPS", "IMU",
        "RPA", "robotic process automation", "UiPath", "Automation Anywhere",
        "Blue Prism", "Power Automate", "Selenium", "Python scripts",
        "workflow automation", "low-code", "no-code", "Zapier", "Make",
        "PLC", "programmable logic controller", "ladder logic",
        "Siemens S7", "Allen-Bradley", "Mitsubishi", "Beckhoff",
        "SCADA", "HMI", "historian", "OPC UA", "OPC DA",
        "industrial automation", "Industry 4.0", "smart factory",
        "digital twin", "simulation", "virtual commissioning",
        "collaborative automation", "human-robot interaction", "HRI",
        "safety", "ISO 10218", "ISO/TS 15066", "functional safety",
    ],

    # ── Database Administration ───────────────────────────────────────────────
    "database_admin": [
        "database administration", "DBA", "database engineer",
        "PostgreSQL", "MySQL", "MariaDB", "Oracle Database", "SQL Server",
        "IBM DB2", "Sybase", "Informix",
        "installation", "configuration", "patching", "upgrades",
        "backup", "restore", "point-in-time recovery", "PITR",
        "RMAN", "pg_dump", "mysqldump", "xtrabackup",
        "replication", "logical replication", "physical replication",
        "streaming replication", "WAL", "binlog",
        "high availability", "HA", "failover", "switchover",
        "Patroni", "PgBouncer", "pgpool-II", "ProxySQL",
        "Always On", "AG", "availability group", "mirroring", "log shipping",
        "RAC", "Oracle Real Application Clusters",
        "performance tuning", "query optimisation", "explain plan",
        "index", "B-tree", "hash", "GIN", "GiST", "covering index",
        "statistics", "ANALYZE", "VACUUM", "autovacuum",
        "partitioning", "table partitioning", "range partition", "list partition",
        "sharding", "horizontal scaling", "vertical scaling",
        "connection pooling", "connection string",
        "security", "roles", "privileges", "row-level security",
        "auditing", "transparent data encryption", "TDE",
        "data masking", "obfuscation",
        "capacity planning", "storage", "IOPS", "tablespace",
        "monitoring", "pg_stat", "slow query log", "performance schema",
        "migration", "Flyway", "Liquibase", "schema versioning",
        "NoSQL", "MongoDB", "Cassandra", "Couchbase", "DynamoDB",
        "Redis", "cache invalidation", "TTL", "eviction policy",
        "graph database", "Neo4j", "ArangoDB",
        "time-series database", "InfluxDB", "TimescaleDB",
    ],

    # ── Technical Writing ─────────────────────────────────────────────────────
    "technical_writing": [
        "technical writing", "documentation", "docs-as-code",
        "API documentation", "developer documentation", "user guide",
        "reference manual", "quick start guide", "tutorial", "how-to",
        "architecture document", "design document", "ADR",
        "architecture decision record", "RFC", "request for comments",
        "Markdown", "reStructuredText", "AsciiDoc", "LaTeX",
        "Sphinx", "MkDocs", "Docusaurus", "GitBook", "Confluence",
        "Swagger", "OpenAPI", "AsyncAPI", "GraphQL schema docs",
        "Javadoc", "JSDoc", "Doxygen", "pydoc",
        "version control", "Git", "GitHub Pages", "ReadTheDocs",
        "content strategy", "information architecture",
        "single sourcing", "DITA", "Darwin Information Typing Architecture",
        "topic-based authoring", "chunking",
        "style guide", "Microsoft Writing Style Guide", "Google Developer Style",
        "plain language", "readability", "Flesch-Kincaid",
        "screenshots", "diagrams", "Mermaid", "PlantUML", "draw.io",
        "video documentation", "screencast", "Loom",
        "localisation", "internationalisation", "translation management",
        "Crowdin", "Phrase", "Transifex",
        "SEO for docs", "search", "Algolia DocSearch",
        "analytics", "feedback", "continuous improvement",
        "JIRA", "GitHub Issues", "content management system", "CMS",
    ],

    # ── IT Support / SysAdmin ─────────────────────────────────────────────────
    "support_sysadmin": [
        "IT support", "system administration", "sysadmin",
        "help desk", "service desk", "L1", "L2", "L3 support",
        "ITIL", "ITSM", "incident management", "problem management",
        "change management", "service request", "CMDB",
        "ServiceNow", "Jira Service Management", "Freshservice", "Zendesk",
        "Windows Server", "Active Directory", "Group Policy", "GPO",
        "WSUS", "SCCM", "Intune", "Endpoint Manager",
        "Linux", "Ubuntu", "CentOS", "RHEL", "Debian",
        "bash", "PowerShell", "Python scripting", "automation",
        "networking", "TCP/IP", "DNS", "DHCP", "WINS",
        "VPN", "firewall", "proxy", "web filter",
        "virtualisation", "VMware", "vSphere", "vCenter", "ESXi",
        "Hyper-V", "KVM", "Xen", "Proxmox",
        "storage", "SAN", "NAS", "iSCSI", "NFS", "CIFS",
        "backup", "Veeam", "Veritas", "Commvault", "Acronis",
        "disaster recovery", "business continuity",
        "patch management", "vulnerability management",
        "antivirus", "EDR", "endpoint protection",
        "Microsoft 365", "Exchange", "SharePoint", "Teams admin",
        "Google Workspace", "Gmail admin", "G Suite",
        "SSO", "LDAP", "SAML", "Okta", "Azure AD",
        "ticketing", "SLA", "escalation", "knowledge base",
        "asset management", "CMDB", "inventory",
        "printing", "imaging", "deployment", "MDM",
        "remote support", "RDP", "VNC", "TeamViewer",
        "monitoring", "Zabbix", "Nagios", "PRTG", "SolarWinds",
    ],

    # ── Supply Chain & Logistics ───────────────────────────────────────────────
    "supply_chain_logistics": [
        "supply chain", "logistics", "operations", "procurement",
        "sourcing", "supplier management", "vendor management",
        "RFQ", "RFP", "RFI", "tender", "contract management",
        "purchase order", "PO", "invoice", "goods receipt",
        "procure-to-pay", "P2P", "source-to-pay", "S2P",
        "inventory management", "stock control", "cycle counting",
        "ABC analysis", "EOQ", "economic order quantity",
        "safety stock", "reorder point", "lead time",
        "warehouse management", "WMS", "picking", "packing", "receiving",
        "FIFO", "LIFO", "FEFO", "bin location", "slotting",
        "transport management", "TMS", "freight", "shipping",
        "last mile delivery", "first mile", "cross-docking",
        "inbound logistics", "outbound logistics", "reverse logistics",
        "3PL", "third-party logistics", "4PL",
        "customs", "import", "export", "Incoterms", "HS code",
        "bill of lading", "airway bill", "commercial invoice",
        "demand planning", "demand forecasting", "S&OP",
        "sales and operations planning", "IBP", "integrated business planning",
        "supply chain visibility", "track and trace", "RFID", "barcode",
        "ERP", "SAP MM", "SAP SD", "SAP WM", "SAP EWM",
        "Oracle SCM", "Blue Yonder", "Kinaxis", "o9 Solutions",
        "sustainability", "ESG", "carbon footprint", "Scope 3",
        "circular economy", "reverse logistics", "returns management",
        "quality management", "ISO 9001", "six sigma", "lean",
        "DMAIC", "PDCA", "kaizen", "5S", "value stream mapping",
    ],
}

# ── Keyword → category mapping ─────────────────────────────────────────────────
_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "software": [
        "software", "backend", "frontend", "fullstack", "full-stack",
        "developer", "engineer", "java", "python", "node", "php",
        "spring", "angular", "react", "vue", "web", "kotlin", "scala",
        "golang", "rust", "ruby", "rails", ".net", "c#",
    ],
    "ai_ml": [
        "ai", "ml", "machine learning", "deep learning", "data science",
        "nlp", "computer vision", "llm", "artificial intelligence",
        "neural", "model", "genai", "generative", "research scientist",
        "applied scientist", "mlops", "mlengine",
    ],
    "cybersecurity": [
        "security", "cyber", "penetration", "soc", "infosec",
        "vulnerability", "forensic", "red team", "blue team",
        "appsec", "devsecops", "compliance", "risk",
    ],
    "cloud": [
        "cloud", "aws", "azure", "gcp", "infrastructure", "platform",
        "sre", "site reliability", "cloud architect",
    ],
    "data": [
        "data engineer", "data pipeline", "etl", "spark", "kafka",
        "databricks", "data platform", "data infrastructure",
    ],
    "bi": [
        "business intelligence", "bi ", "power bi", "tableau", "looker",
        "analytics", "reporting", "qlik", "data analyst",
    ],
    "devops": [
        "devops", "sre", "reliability", "platform engineer",
        "infrastructure", "jenkins", "ci/cd", "gitops",
    ],
    "mobile": [
        "mobile", "ios", "android", "flutter", "react native",
        "swift", "kotlin", "app developer",
    ],
    "embedded_iot": [
        "embedded", "firmware", "iot", "rtos", "fpga",
        "microcontroller", "hardware", "bare metal",
    ],
    "project_management": [
        "project manager", "pmp", "scrum master", "product owner",
        "agile coach", "program manager", "delivery manager", "pmo",
    ],
    "accounting_finance": [
        "account", "finance", "audit", "tax", "controller",
        "treasurer", "erp", "sap", "fp&a", "cfo", "actuar",
    ],
    "hr_talent": [
        "hr", "human resource", "talent", "recruiter", "recruitment",
        "people", "hrbp", "compensation", "benefits", "l&d",
    ],
    "legal_compliance": [
        "legal", "compliance", "counsel", "lawyer", "attorney",
        "regulatory", "gdpr", "aml", "kyc", "contract",
    ],
    "marketing_growth": [
        "marketing", "growth", "seo", "sem", "content", "brand",
        "demand gen", "performance marketing", "digital marketing",
    ],
    "sales_crm": [
        "sales", "account executive", "sdr", "bdr", "crm",
        "salesforce", "customer success", "revenue", "business development",
    ],
    "product_management": [
        "product manager", "product owner", "cpo", "product lead",
        "product analyst", "product strategist",
    ],
    "ux_design": [
        "ux", "ui", "design", "designer", "figma", "user experience",
        "user interface", "product design", "visual design",
    ],
    "qa_testing": [
        "qa", "quality assurance", "quality engineer", "tester",
        "test automation", "sdet", "testing",
    ],
    "networking": [
        "network", "cisco", "juniper", "routing", "switching",
        "firewall", "infrastructure", "noc", "ccna", "ccnp",
    ],
    "blockchain_web3": [
        "blockchain", "web3", "solidity", "ethereum", "defi",
        "smart contract", "nft", "crypto",
    ],
    "game_dev": [
        "game", "unity", "unreal", "godot", "gameplay",
        "game developer", "game engineer", "game designer",
    ],
    "erp_sap": [
        "sap", "erp", "oracle erp", "dynamics", "abap",
        "business analyst erp", "functional consultant",
    ],
    "healthcare_it": [
        "healthcare it", "health informatics", "ehr", "emr", "fhir",
        "clinical", "hospital", "medtech", "health tech",
    ],
    "edtech": [
        "edtech", "e-learning", "lms", "education technology",
        "instructional design", "curriculum",
    ],
    "scientific_research": [
        "research", "scientist", "bioinformatics", "computational",
        "hpc", "matlab", "simulation", "laboratory",
    ],
    "robotics_automation": [
        "robot", "ros", "automation", "rpa", "uipath", "plc",
        "scada", "autonomous", "drone", "mechatronics",
    ],
    "database_admin": [
        "dba", "database admin", "database engineer", "postgresql admin",
        "mysql admin", "oracle dba", "sql server",
    ],
    "technical_writing": [
        "technical writer", "documentation", "doc engineer",
        "developer advocate", "devrel", "content engineer",
    ],
    "support_sysadmin": [
        "support", "sysadmin", "system administrator", "help desk",
        "service desk", "it technician", "infrastructure support",
    ],
    "supply_chain_logistics": [
        "supply chain", "logistics", "procurement", "sourcing",
        "operations", "warehouse", "inventory", "demand planning",
    ],
}


def select_vocab(job_title: str, job_requirements: list[str] | None = None) -> list[str]:
    """
    Return a deduplicated list of vocabulary terms relevant to this job.
    Always includes 'common'. Adds category-specific lists based on keyword
    matching against the job title and requirements.
    """
    title_lower = job_title.lower()
    req_text    = " ".join(job_requirements or []).lower()
    search_text = f"{title_lower} {req_text}"

    selected = list(_VOCAB["common"])
    matched: set[str] = set()

    for category, keywords in _CATEGORY_KEYWORDS.items():
        if any(kw in search_text for kw in keywords):
            if category not in matched:
                matched.add(category)
                selected.extend(_VOCAB.get(category, []))

    # Fallback: if nothing matched, include software (most common)
    if not matched:
        selected.extend(_VOCAB["software"])

    # Deduplicate while preserving order
    seen: set[str] = set()
    result: list[str] = []
    for term in selected:
        key = term.lower()
        if key not in seen:
            seen.add(key)
            result.append(term)

    return result


# ── Utility: list all categories ──────────────────────────────────────────────
def list_categories() -> list[str]:
    """Return all available vocabulary category names."""
    return list(_VOCAB.keys())


# ── Utility: get raw category vocab ──────────────────────────────────────────
def get_category_vocab(category: str) -> list[str]:
    """Return the raw term list for a specific category, or [] if unknown."""
    return _VOCAB.get(category, [])