export interface Notification {
  id: string;
  userId: string;
  type: 'USER_BLOCK' | 'USER_UNBLOCK' | 'ROLE_UPDATE' | 'APPLICATION_STATUS_UPDATE'
      | 'JOB_UPDATED' | 'JOB_QUOTA_REACHED' | 'JOB_CLOSED'
      | 'INTERVIEW_INVITE' | 'INTERVIEW_JOIN_REQUEST'
      | 'INTERVIEW_PROPOSAL_SENT' | 'INTERVIEW_PROPOSAL_DECLINED'
      | 'INTERVIEW_RESCHEDULE_PROPOSED' | 'INTERVIEW_RESCHEDULE_DECLINED' | 'INTERVIEW_RESCHEDULE_CANCELLED'
      | 'INTERVIEW_DELEGATION_REQUESTED' | 'INTERVIEW_DELEGATION_DECLINED' | 'INTERVIEW_DELEGATION_CANCELLED'
      | 'CANDIDATE_FLAGGED'
      | 'OFFER_SENT' | 'OFFER_REVISED' | 'OFFER_ACCEPTED' | 'OFFER_DECLINED' | 'OFFER_WITHDRAWN';
  title: string;
  body: string;
  read: boolean;
  createdAt: string;
  relatedEntityType?: string;
  relatedEntityId?: string;
}
